### ISSUE TITLE
TODO before resubmitting

### ISSUE THREAD

**Issue by davydden** [davydden/large-strain-matrix-free#68]
**Notes from 8.6.19 discussion**

TODO:

- [x] combine Section 4 (framework) with Section 6 (GMG) and make GMG very concise. @davydden 
- [x] ~~@davydden @jppelteret  is to maybe re-run breakdown time analysis and update plots/LIKWID results~~
- [x] with Martin's help maybe get LIKWID on AVX512
- [x] ~~with Martin's help maybe get some large scale simulations.~~ let's stick with what we have
- [x] drop Figure 5 @davydden 
- [x] rewrite first paragraph in Abstract, make concise  https://github.com/davydden/large-strain-matrix-free/pull/87
- [x] improve Clevenger Timo,... @davydden 
- [x] update Martin Kormann 2019 paper @davydden 
- [x] ~~drop deal.II 8.5 @davydden~~  EDIT: I see that @masterleinad cites it for manifold info, I think it's ok to keep it.
- [x] prepare e-mail for Martin @davydden 

------- 
Reviewer 1: 

On the other hand, the presentation would need a substantial improvement and not just adding new paragraphs here and there. For instance, it is still hard for me to tell what kind of geometric multigrid is used. Here a simple reference on an unpublished paper in Section 4 is not enough. Also you still claim “you propose” a multigrid here but the section is still short and unprecise.  Some other things that I disliked:
1.) The abstract is now very long and not very concise.
2.) Abstract and introduction start with the same paragraph.
3.) Chapter ~~3~~ 4 has been added but not been properly integrated. Now the geometric multigrid of deal.II is described here but then there is the geometric multigrid section later on.
4.) The citation is still random. E.g. you should refer to [1] when introducing deal.II’s matrix-free framework and give a reference for the matrix-free framework that you introduce in section 5.
Before resubmission the authors should make an effort to concisely present their content.

-----

Reviewer 2 (summary):

1. Start from bottlenecks (in Trilinos?): memory layout, bandwidth, irregular memory access, profiling   
2. He mentions in many cases “pre-existing deal.II functionality”, I think implying that we did not do enough new
3. No performance analysis of SIMD vectorization
4. No performance evaluation of the multigrid is presented
5. Old architectures (chips from 2011/2012)
6. MF: how could performance be improved (code-restructuring)? What exactly obstructs performance? Other bottlenecks?
7. MF: analytic assessment of the algorithmic requirements. Flops in MF depending on degree? How many memory accesses? Compare to measured
